name: Sonic Audit Test
on: [push, pull_request]

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Use go
        uses: actions/setup-go@v3
        with:
            go-version: '1.22.8'

      - name: Install dependencies
        run: go get

      - name: Tests
        run: go test ./...